http:
  # Middleware for handling local .localhost domains
  middlewares:
    localhost-redirect:
      redirectRegex:
        regex: "^http://(.*)\\.localhost/(.*)"
        replacement: "http://${1}.localhost/$2"
        permanent: true

  # Routers for .localhost domains
  routers:
    localhost-catchall:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.localhost`)"
      middlewares:
        - localhost-redirect
      service: noop
      priority: 1

  # No-op service that does nothing - just needed for the catchall router
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://localhost"